### ISSUE TITLE
Les geek lunches à venir ne s'affichent pas correctement

### ISSUE THREAD

**Issue by joel-mognol** [MTES-MCT/numerique#11]
Le script  numerique/geek-lunch/index.md traite différemment les geek lunches à venir et passés.
![clipboard01](https://user-images.githubusercontent.com/34911806/36856199-b47fd1d2-1d75-11e8-9657-fdb2e9061b5b.jpg)

**Comment by ouhouhsami** [comment]
done

**Comment by joel-mognol** [comment]
Merci. Cela m'a permis de tester le système de suivi des bugs.
