### ISSUE TITLE
Addresse mail Locat.io

### ISSUE THREAD

**Issue by AntoineAugusti** [MTES-MCT/numerique#16]
L'adresse contact@locat.io.beta.gouv.fr n'existe pas. Est-ce `contact@locatio.beta.gouv.fr` ?

Sur la page https://mtes-mct.github.io/numerique/startup/locat.io.html

**Comment by ouhouhsami** [comment]
cc @hrlwfres ?

**Comment by hrlwfres** [comment]
**contact@locatio.beta.gouv.fr** fonctionne

**Comment by hrlwfres** [comment]
De manière générale, locat.io n'existe plus nul part et a été remplacé par locatio "en un mot"

**Comment by ouhouhsami** [comment]
thanks

**Comment by AntoineAugusti** [comment]
La conf ne marche pas quand j'essaie de mail depuis mon adresse du ministère. J'ai un "undelivered mail returned to sender".

```
This is the mail system at host mo53.mail-out.ovh.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<matthieu.heurtel@developpement-durable.gouv.fr>: host
    relternet-01.developpement-durable.gouv.fr[194.5.170.13] said: 554 5.7.1
    <matthieu.heurtel@developpement-durable.gouv.fr>: Recipient address
    rejected: mail refuse car emetteur interne depuis internet (in reply to
    RCPT TO command)
```

**Comment by ouhouhsami** [comment]
alors, c'est un pb de serveur ovh de beta.gouv.fr <=> nos serveurs de mail. Le problème est "connu".

**Comment by hrlwfres** [comment]
Je recois tes mails pourtant 
![image](https://user-images.githubusercontent.com/3857484/37908113-68bf1bf4-3107-11e8-83c6-9b3fdd42865e.png)

**Comment by hrlwfres** [comment]
En revanche j'ai essayé d'utiliser l'email pour envoyer un message de test je n ai rien reçu

**Comment by AntoineAugusti** [comment]
J'ai renvoyé depuis mon adresse perso @hrlwfres ensuite. Le problème est quand tu mail depuis developpement-durable.gouv.fr vers beta.gouv.fr

**Comment by ouhouhsami** [comment]
c'est ça qu'est assez dingo :) ... c'est la communication entre les serveurs mail developpement-durable.gouv.fr <=> beta.gouv.fr

**Comment by hrlwfres** [comment]
J'ai reçu deux messages de ta part @AntoineAugusti

**Comment by hrlwfres** [comment]
![image](https://user-images.githubusercontent.com/3857484/37908336-3e20dc6a-3108-11e8-84f7-eed0ad754cf8.png)

**Comment by AntoineAugusti** [comment]
Super, donc ça crache une erreur mais tu reçois quand même ? Well 🤷‍♂️

**Comment by hrlwfres** [comment]
tu m avais ciblé spécifiquement 
Car Matthieu a reçu mes messages tests mais pas moi :D
